branch-defaults:
  aws_distribute:
    environment: django-distribute
    group_suffix: null
global:
  application_name: didim365-bulletin-board
  branch: null
  default_ec2_keyname: didim365_homework
  default_platform: Python 3.6
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
